apiVersion: appsody.dev/v1beta1
kind: AppsodyApplication
metadata:
  annotations:
    commit.image.appsody.dev/author: Jerome Boyer <boyerje@us.ibm.com>
    commit.image.appsody.dev/committer: Jerome Boyer <boyerje@us.ibm.com>
    commit.image.appsody.dev/contextDir: /simulator
    commit.image.appsody.dev/date: Tue Jan 7 21:42:49 2020 -0800
    commit.image.appsody.dev/message: Merge branch 'master' of https://github.com/jbcodeforce/refarch-reefer-ml
    image.opencontainers.org/created: "2020-01-08T17:00:34-08:00"
    image.opencontainers.org/documentation: https://github.com/jbcodeforce/refarch-reefer-ml
    image.opencontainers.org/revision: 44ee771eaa7eb8d5392717ef971f5d7009d8aa3c-modified
    image.opencontainers.org/source: https://github.com/jbcodeforce/refarch-reefer-ml/tree/master
    image.opencontainers.org/url: https://github.com/jbcodeforce/refarch-reefer-ml
    stack.appsody.dev/configured: docker.io/appsody/python-flask:0.1
    stack.appsody.dev/created: 2019-11-14T10:29:19+0000
    stack.appsody.dev/revision: b3e8a19b0a4b66a69daa8d1106f37bbe4167693a
    stack.appsody.dev/tag: appsody/python-flask:0.1.6
  creationTimestamp: null
  labels:
    image.opencontainers.org/title: reefer-simulator
    stack.appsody.dev/version: 0.1.6
  name: reefer-simulator
spec:
  applicationImage: dev.local/reefer-simulator
  createKnativeService: false
  expose: true
  livenessProbe:
    failureThreshold: 12
    httpGet:
      path: /health
      port: 8080
    initialDelaySeconds: 5
    periodSeconds: 2
  monitoring:
    labels:
      k8s-app: reefer-simulator
  service:
    annotations:
      prometheus.io/scrape: "true"
    port: 8080
    type: NodePort
  stack: python-flask
  version: 1.0.0
status: {}
