site_name: Reefer Container Predictive Maintenance
repo_url: https://github.com/ibm-cloud-architecture/refarch-reefer-ml
nav:
  - Introduction: index.md
  - Enablement Content:
    - Cloud Pak approach: cp-approach.md
    - Open source approach: oos-approach.md
    - Methodology used: https://ibm-cloud-architecture.github.io/refarch-data-ai-analytics/methodology/
  - Collect:
    - Preparing data for demonstration:
      - Get products into postgresql: collect/products-postgres.md
      - Generate telemetry data: collect/generate-telemetry.md
    - Collect data with open source solution: collect/oss-collect-data.md
    - Collect data with cloud pak for data: collect/cp4d-collect-data.md
  - Organize: organize/readme.md
  - Analyze: 
    - Define the anomaly detection scoring model with OSS: analyze/oss-ml-dev.md
    - Reefer anomaly detection problem: analyze/predictive-maintenance.md
  - Infuse:
    - Develop the simulation app: infuse/simul-app.md
    - Develop scoring app with cloud pak for application: infuse/dev-scoring.md
    - Build and run the solution on Openshift: infuse/build-run.md
    - Engineer dispatching with Business process with Cloud Pak for Automation: infuse/bpm.md
    - Run integration tests: infuse/integration-tests.md
  
  - Reefer solution implementation project: https://ibm-cloud-architecture.github.io/refarch-kc/
theme: 
  name: material
extra_css: ["extra.css"]
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - pymdownx.smartsymbols
  - pymdownx.superfences