# Default values for kcontainer-reefer-simulator.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
revisionHistoryLimit: 1

image:
  repository: ibmcase/kcontainer-reefer-simulator
  tag: v0.0.10
  pullPolicy: Always
  pullSecret: null

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
service:
  type: ClusterIP
  port: 8080
ingress:
  enabled: false
kafka:
  brokersConfigMap: demo-kafka-brokers
  telemetryTopicName: reeferTelemetries
  containerTopicName: containers
  capemSecret: es-cert-pem
eventstreams:
  enabled: true
  apikeyConfigMap: demo-es-apikey
serviceAccountName: kcontainer-runtime
