name: Build & push images for 'reefer ML demo'
on:
  push:
    branches:
      - master
    paths-ignore:
      - 'docs/**'
      - 'cassandra/'
      - 'consumer/'
      - 'data_schema/'
      - 'docker/'
      - 'ml/'
      - 'postgresql/'
      - 'scripts/'
      - '**/chart/'

jobs:
  build-docker-images:
    if: startsWith(github.repository, 'ibm-cloud-architecture/')
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Bump version and push tag
      id: bump-version-action
      uses: anothrNick/github-tag-action@master
      env:
        DEFAULT_BUMP: patch
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Build the simulator docker image
      id: build-simulator-image
      run: |
        docker login -u ${DOCKER_U} -p ${DOCKER_P}
        cd ${WORKDIR}
        docker build . --file ${DOCKERFILE} --tag ${IMAGE_NAME}:${IMAGE_TAG}
        docker tag ${IMAGE_NAME}:${IMAGE_TAG} ${IMAGE_NAME}:latest
        docker push ${IMAGE_NAME}
      env:
        DOCKER_U: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_P: ${{ secrets.DOCKER_PASSWORD }}
        WORKDIR: simulator
        DOCKERFILE: Dockerfile
        IMAGE_NAME: ibmcase/kcontainer-reefer-simulator
        IMAGE_TAG: ${{ steps.bump-version-action.outputs.new_tag }}
    